### PR TITLE
fix search with spaces

### PR DESCRIPTION
**Pull request by s-kostyaev**
for searches like "func New"

### CODE REVIEW

**Comment by s-kostyaev** [comment]
Also add some improvements. I can split it in separate PRs if you want.

**Comment by youngker** [comment]
Thank you.

**Comment by dbldippy** [comment]
I mean like in the previous implementation. Often, my searches go like this:

1. Let's try M-. directly on the specifier in the code:
    bar.*baz
2. Hm, too many entries. Let me quickly without quitting the search drill down a bit:
   -f foo bar.*baz

**Comment by youngker** [comment]
Hi all
I released v 0.5.0
you can set a file pattern with "C-c f" in helm-window
and set a ignore-case with "C-c i".

I don't know if this is better than command input (-f) but please check it.

**Pull request merged**
